name: Test

on:
  push:  # Run on all branches
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/powershell:lts-7.4-ubuntu-22.04
    name: Test PowerShell Scripts
    steps:
      - uses: actions/checkout@v4

      - name: Run Tests
        shell: pwsh
        run: |
          pwsh --version
          ./test.ps1
